apiVersion: tekton.dev/v1
kind: PipelineRun

metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/zregvart/collector?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "500"
    pipelinesascode.tekton.dev/on-event: '[push]'
    pipelinesascode.tekton.dev/on-target-branch: '[master]'
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: acs
    appstudio.openshift.io/component: collector
    pipelines.appstudio.openshift.io/type: build
  name: collector-on-push
  namespace: zregvart-tenant

spec:

  params:
  - name: dockerfile
    value: collector/container/konflux.Dockerfile
  - name: git-url
    value: '{{source_url}}'
  - name: output-image
    value: quay.io/redhat-user-workloads-stage/zregvart-tenant/acs/collector:{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  - name: rebuild
    value: 'true'
  - name: hermetic
    value: "true"
  - name: clone-submodules
    value: 'true'
  - name: build-source-image
    value: 'true'
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
  - name: subscription-manager-activation-key
    secret:
      secretName: subscription-manager-activation-key
  timeouts:
    pipeline: 1h30m0s
  pipelineRef:
    params:
      - name: bundle
        value: quay.io/redhat-appstudio-tekton-catalog/pipeline-docker-build@sha256:e3e37d1d6749796f8aec1499af1cef9aa77f759229dfeaad90dbee70e34459f3
      - name: name
        value: docker-build
      - name: kind
        value: pipeline
    resolver: bundles
  taskRunTemplate:
    podTemplate:
      env:
        - name: DEBUG
          value: '1'
